package:
  name: nbsetooptools
  version: '0.1.0'

requirements:
  build:
    - python
  run:
    - funcsigs
    - notebook
    - python

source:
  path: ../

about:
  home: https://github.com/anaconda-server/anaconda-notebook
  license: TBD
